### ISSUE TITLE
Validator and Converter

### ISSUE THREAD

**Issue by JMante1** [SynBioDex/SbolStandardWebsite#50] opened 2020-10-16 18:41 UTC
the fact that the validator and converter lead to the same page might be confusing

**Comment by cjmyers** [comment] 2020-10-16 19:02
They are actually different pages.  Is that not what you are seeing?

**Comment by JMante1** [comment] 2020-10-16 19:46
Sorry they are slightly different pages but the validator has conversion options on the page which is confusing

**Comment by cjmyers** [comment] 2020-10-16 20:17
Yeah, that is by design. They are the same thing, but different UI.  We had some people complain that the validator had too many options for someone just wanting to convert a GenBank file.  I don't use the converter front-end myself, since the validator is more full-feature.

**Comment by PrashantVaidyanathan** [comment] 2020-11-16 00:33
I'm closing this issue for now since it seems that the pages are showing up as intended. This can be re-opened in case there are additional actionable items.

**Closed by PrashantVaidyanathan** 2020-11-16 00:33 UTC
